DROP TABLE IF EXISTS rappers;
DROP TABLE IF EXISTS vocalists;
DROP TABLE IF EXISTS dancers;

CREATE TABLE rappers (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    kgroup TEXT NOT NULL,
    name TEXT NOT NULL
);

CREATE TABLE vocalists (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    kgroup TEXT NOT NULL,
    name TEXT NOT NULL
);

CREATE TABLE dancers (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    kgroup TEXT NOT NULL,
    name TEXT NOT NULL
);